### PR TITLE
Add omero-java-gateway as submodule

### PR DESCRIPTION
**Pull request by dominikl**
Is that everything which is needed to add the `omero-java-gateway` as submodule @joshmoore ?

### CODE REVIEW

**Comment by joshmoore** [comment]
This PR will likely be red unless you point it at the necessary PR from your fork. But this should be the only change necessary to have this built in devspace. Just coordinate with @mtbc for re-runs.

**Comment by dominikl** [comment]
Then I'll wait until https://github.com/ome/omero-java-gateway/pull/1 is merged. Having a PR which points to my fork isn't really useful.

**Comment by joshmoore** [comment]
Ha. Green anyway, which I guess means that `gradle` works fine? ...
https://github.com/ome/omero-build/blob/4a3227d80ace0daa487b81d4d2c0a80ac2a2f858/settings.gradle

Nope. This file needs updating.

> Having a PR which points to my fork isn't really useful.

Pointing omero-build PRs at personal forks is basically a must to be able to test accurately. (You can check all the previous PRs to see how temporarily the fork is used, then when the fork is merged, this repo gets bumped to use the new master.)

**Comment by joshmoore** [comment]
```
> Task :omero-gateway:compileJava
/src/omero-java-gateway/src/main/java/omero/gateway/facility/SearchFacility.java:115: error: cannot find symbol
                service.setCaseSensitive(false);
                       ^
  symbol:   method setCaseSensitive(boolean)
  location: variable service of type SearchPrx
```

Your branch has a dependency on https://github.com/ome/omero-blitz/pull/17

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
Tested with the new BF 6.1.0-m1 (which includes new guava version)
the "extraction" of omero-java-gateway from omero-blitz is now possible
We cannot include BF 6.1. yet since the omero pyramid reading is currently broken.
Excluding this PR for now

--exclude

**Pull request closed without merging**
