### PR TITLE
docker: update build for Ice 3.7

### PR DESCRIPTION
**Pull request by joshmoore**

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-build-push#1](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build-push/1/). See the [console output](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build-push/1/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - Dockerfile

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-build-push#52](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build-push/52/). See the [console output](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build-push/52/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - Dockerfile

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-build-push#106](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build-push/106/). See the [console output](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-build-push/106/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - Dockerfile

--conflicts

**Comment by joshmoore** [comment]
closing to prevent conflict notifications.

**Pull request closed without merging**
