### PR TITLE
jenkins

### PR DESCRIPTION
**Pull request by jburel**
retrieve properties from different job
See https://github.com/ome/omero-gradle-plugins/pull/8

cc @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
:+1: via https://github.com/ome/omero-gradle-plugins/pull/8#issuecomment-492668397

**Comment by sbesson** [comment]
Pushed dc5a84b  to fix the expected location of the properties file - see  https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build-build/39/ .

**Comment by sbesson** [comment]
--exclude

**Comment by joshmoore** [comment]
This will likely need to get sorted for latest-ci: see https://github.com/ome/omero-gradle-plugins/pull/8#issuecomment-496818404

**Comment by joshmoore** [comment]
Added `--hotfix` to the `--exclude` in https://github.com/ome/omero-build/pull/21#issuecomment-493073436 in order to fix https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-build-build/11/console

**Comment by joshmoore** [comment]
As in https://github.com/ome/omero-gradle-plugins/pull/9#issuecomment-498707594, I've removed "exclude" to get merge-ci passing again.

**Pull request merged**
