### PR TITLE
Update master submodules

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: ome/omero-build
Already up-to-date.

Repository: ome/omero-blitz
Updating 93c3db2..a986bd3
Previously merged:
  - PR 101 mtbc 'Fix fileset ID lookup among managed repository processes.'
  - PR 102 mtbc 'remove PublicRepositoryI.DEFAULT_SKIP'
  - PR 97 mtbc 'Bump test dependency.'
  - PR 96 mtbc 'Update help links for CLI importer.'
  - PR 93 jburel 'info in log'
  - PR 86 jburel 'Test review: remove junit'
  - PR 94 mtbc 'Fix import-as by group owners.'
  - PR 90 melissalinkert 'Implement setROIName in OMEROMetadataStoreClient'
  - PR 89 mtbc 'Have security check limit file query by fileset ID.'
  - PR 85 mtbc 'Have reset password use SQL to bypass 2019-SV3 restrictions.'
  - PR 83 mtbc 'Update changelog for v5.5.6 release.'
  - PR 78 jburel 'Name in log'
  - PR 82 mtbc 'Document light admin restrictions on graph operations.'
  - PR 81 jburel 'unit test'
  - PR 80 chris-allan 'Expand user session creation abilities'
  - PR 76 joshmoore 'model: Handle infinities in generated conversions'
  - PR 65 joshmoore 'cleanup and expose import keep alives (see #64)'
  - PR 75 joshmoore 'Remove bin/omero references'
  - PR 72 joshmoore 'Throw early on null tablePrx'

Repository: ome/omero-common
Updating e5353dd..57a842e
Previously merged:
  - PR 25 jburel 'remove junit'
  - PR 24 mtbc 'Update changelog for v5.5.5 release.'
  - PR 23 jburel 'unit test'
  - PR 21 chris-allan 'Expand user session creation abilities'
  - PR 22 chris-allan 'Add `omero.pixeldata.max_projection_bytes` to dependency stack'

Repository: ome/omero-gateway-java
Updating 9220153..9d24cd4
Previously merged:
  - PR 37 jburel 'license file'
  - PR 34 dominikl 'Improve error message'
  - PR 36 mtbc 'Note the client IP address when connecting to the server.'
  - PR 35 mtbc 'Update changelog for v5.6.3 release.'
  - PR 32 mtbc 'Bump TestNG version to match other components of OMERO.'
  - PR 31 jburel 'Migrate unit test from openmicroscopy'
  - PR 28 dominikl 'Make sure default wss port is set'
  - PR 25 dominikl 'Just adds missing @Deprecated annotations'
  - PR 26 dominikl 'Check for pixel size unit == pixel'
  - PR 21 dominikl 'Support websocket URLs'
  - PR 15 dominikl 'Do not handle infinite, nan, etc. cases for pixel sizes'
  - PR 23 mtbc 'Relax server version check for >=5.5 semantic versioning.'
  - PR 22 dominikl 'Deprecate unused CacheService'

Repository: ome/omero-model
Updating 3d38372..a05f91a
Previously merged:
  - PR 58 mtbc 'Revert "More thoroughly clean up current admin privileges table."'
  - PR 54 mtbc 'More thoroughly clean up current admin privileges table.'
  - PR 53 jburel ' BF 6.5.1'
  - PR 51 mtbc 'Provide SQL means of fetching users' pretty name and e-mail.'
  - PR 52 jburel 'remove junit'
  - PR 50 mtbc 'Update changelog for v5.5.5 release.'
  - PR 45 mtbc 'From the generated SQL clean up an apparent nonsense string.'
  - PR 48 jburel 'unit test'
  - PR 47 chris-allan 'Add `omero.pixeldata.max_projection_bytes` to dependency stack'
  - PR 44 dgault 'Bump Bio-Formats version to 6.3.0'
  - PR 43 joshmoore 'Handle nulls on findLink-style model methods (fix #65)'

Repository: ome/omero-renderer
Updating b18510d..a435b0f
Previously merged:
  - PR 13 jburel 'remove junit'
  - PR 12 mtbc 'Update changelog for v5.5.5 release.'
  - PR 11 jburel 'unit test'

Repository: ome/omero-romio
Updating 53849c0..0401081
Previously merged:
  - PR 22 mtbc 'Bump to v5.6.0 ready for tag.'
  - PR 21 chris-allan 'Allow sub-classes, etc. to call getPath()'
  - PR 19 jburel 'remove junit'
  - PR 18 mtbc 'Update changelog for v5.5.5 release.'
  - PR 17 jburel 'unit test'
  - PR 16 chris-allan 'Allow for the retrieval of current file mode'
  - PR 15 mtbc 'Improve message formatting for exception.'

Repository: ome/omero-server
Updating 191a108..1c5665f
Previously merged:
  - PR 104 jburel 'adjust tests'
  - PR 101 chris-allan 'Fail early if we are in read-only mode'
  - PR 99 mtbc 'Restore exception handling in full-text indexer.'
  - PR 100 mtbc 'Add note about binary access restrictions on groups.'
  - PR 91 mtbc 'More cleanly adapt basic security system for read-only mode.'
  - PR 73 mtbc 'Catch fewer exceptions in full-text indexer.'
  - PR 92 mtbc 'Move check into helper of admin privileges from user config.'
  - PR 87 mtbc 'Have even read-only servers leave session loaded.'
  - PR 90 jburel 'Test review: remove junit'
  - PR 86 mtbc 'deprecate LightAdminPrivilegesSecurityFilter'
  - PR 88 mtbc 'Fix unit tests broken by security vulnerability work.'
  - PR 85 mtbc 'Update changelog for v5.5.6 release.'
  - PR 81 jburel 'unit test'
  - PR 78 chris-allan 'Only flush if we are in read-write mode'
  - PR 79 chris-allan 'Expand user session creation abilities'
  - PR 71 mtbc 'Ensure that the event context has sudoer.omeName loaded.'
  - PR 75 mtbc 'allow "Fake" to be added to DB format table of image readers'
  - PR 72 mtbc 'Fix import from wrong JAR.'
  - PR 67 mtbc 'Have full-text indexer retry as non-batch when bridge fails.'
  - PR 57 joshmoore 'Full text additions'

Generated by build [OMERO-BUILD-submodules#545](https://ci.openmicroscopy.org/job/OMERO-BUILD-submodules/545/).

----
--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
```
ERROR: zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
2389
```

**Comment by joshmoore** [comment]
The error here is the same one I ran into trying to build Mark's PR:

```
Step 13/46 : RUN python -m pip install https://github.com/ome/zeroc-ice-ubuntu1804/releases/download/0.2.0/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl
2383 ---> Running in ee52d9ac9c4c
2384ERROR: zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
2385ERROR: Service 'omero' failed to build: The command '/bin/sh -c python -m pip install https://github.com/ome/zeroc-ice-ubuntu1804/releases/download/0.2.0/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl' returned a non-zero code: 1
```

**Comment by sbesson** [comment]
Reporting quickly a previous background investigation of the root of the Travis issue: the last known passing builds was https://travis-ci.org/github/ome/omero-build/builds/618342289 and it started failing in https://travis-ci.org/github/ome/omero-build/builds/618736509.

Looking at the timestamps/logs, it looks like the problem arises from the switch of the `openmicroscopy` Docker image to use JDK11/Ubuntu18.04 in https://github.com/ome/openmicroscopy/commit/78fba4188876ac5093429fd1f6a675b505085a89. I am still unclear why the 

I had briefly tried switching the base image of this repo to match the one in `openmicroscopy` without success - https://github.com/sbesson/omero-build/commit/26e743a09f06fd6c1438c65aa12fd8b1d9b841f4

**Comment by joshmoore** [comment]
Yep. That's about how far I got as well. The underlying Python is now 3.5 and the wheel won't import.

**Pull request merged**
